name: oktsss
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: oktsss
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: namemf224/oktsss
          username: '${{ secrets.DOCKER_USERNAME }}'
          password: '${{ secrets.DOCKER_PASSWORD }}'
